@startuml
hide empty description
[*] --> Closed
Closed : passing requests through

Closed -> Open : [failure rate above threshold]
Open : blocking requests

Open -> Half_Open : [after wait duration]
Half_Open : pass some requests through to test availability

Half_Open -> Closed : [failure rate below threshold]
Half_Open -> Open : [failure rate above threshold]
@enduml