version: '3.1'

services:

  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
